        let body = document.querySelector('body');
        // let yellow = document.querySelector('.yellow');
        function over1(){
            body.classList.add('yellow');
        }
        function our1(){
            body.classList.remove('yellow');
        }
                function over2(){
            body.classList.add('green');
        }
        function our2(){
            body.classList.remove('green');
        }
                function over3(){
            body.classList.add('gray');
        }
        function our3(){
            body.classList.remove('gray');
        }
